version: '3'

services:

    php:
        build:
            context: ./
            dockerfile: Dockerfile
        restart: always
        volumes:
            - ./www:/var/www/html
        container_name: docker_php
        ports:
            - "5001:80"
